import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import Carousels from './Carousels'
import About from './About/About'
import Advantages from './About/Advantages'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <Navbar />
    //     <body className={inter.className}>{children}</body>
    // </html>

  <div>
    <Navbar />
    
    {children}

    <Footer />
  </div>

  )
}
